// Bundle the website's Markdown checks for the md2xarticle agent skill, which
// runs with plain node and no installed dependencies.
import * as esbuild from 'esbuild';
import { join, resolve } from 'node:path';

const projectRoot = resolve(new URL('..', import.meta.url).pathname);
const outfile = join(projectRoot, 'skills/md2xarticle/scripts/studio-core.mjs');

await esbuild.build({
  entryPoints: [join(projectRoot, 'src/core.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  minify: true,
  legalComments: 'none',
  banner: { js: '// Generated by scripts/build-skill.mjs from src/core.ts. Do not edit; run pnpm build:skill.' },
  logLevel: 'info',
});
console.log('✓ skill bundle → skills/md2xarticle/scripts/studio-core.mjs');
